config/routes.rb
Rails.application.routes.draw do

  root 'draft#welcome'

  resources :drafts, only: [] do
    resource :recap, only: [:show]
    resources :autodrafts, only: [:index, :create, :destroy, :update], shallow: true
  end


  devise_for :players
  get 'authentication/sign_in', as: :sign_in

  get 'new/create-draft' => 'draft#new', as: :new_draft
  post 'new/create-draft' => 'draft#create', as: :create_draft
  get 'new/:id/add-players' => 'draft#add_players', as: :add_players
  post 'new/:id/add-player' => 'draft#add_player', as: :add_player
  get 'new/:draft_id/add-draftees' => 'draftables#batch_new',
    as: :add_draftable
  post 'new/:draft_id/add-draftees' => 'draftables#batch_create',
    as: :save_draftables
  get 'new/:id/review' => 'draft#review', as: :review_draft
  post 'new/:id/start' => 'draft#start', as: :start_draft

  get 'picks/:draft_id/:player_id/(:token)' => 'picks#new', as: :pick
  post 'picks/make/:draft_id/:draftable_id' => 'picks#make', as: :make_pick
  get 'picks/make/:draft_id/:player_id/:draftable_id/:token' =>
    'picks#make', as: :make_pick_from_email

  get 'players/show/:draft_id' => 'players#show', as: :player_page
  get 'players/all_picks/:draft_id' => 'players#all_picks', as: :all_picks

  if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/emails"
  end
end

app/models/draft.rb
class Draft < ActiveRecord::Base
  has_and_belongs_to_many :players
  has_many :picks
  has_many :draftables

  validates :name, presence: true

  def current_pick
    picks.where(draftable:nil).order(:number).first
  end

  def remaining_draftables
    draftables.joins('left outer join picks on draftables.id = picks.draftable_id').
      select('draftables.*, picks.id as pick_id').where('picks.id is null').
      order(:rank)
  end

  def recent_picks
    picks.where('number < ?', current_pick.number).order(number: :desc).limit(5)
  end

  def most_recently_made_pick
    picks.where.not(draftable:nil).order(number: :desc).first
  end

  def next_5_picks
    picks.where(draftable:nil).order(:number).limit(5)
  end

  def next_pick_for(player)
    current_pick_id = current_pick.id
    picks.where(draftable:nil, player: player).where.not(id: current_pick_id).
      order(:number).first
  end

  def surrounding_picks(count)
    current_number = current_pick.number
    picks.where(number: current_number-2..current_number+count-3)
  end

  def draftable_available(draftable_id)
    picks.where(draftable_id: draftable_id).empty?
  end

  def is_over?
    current_pick == nil
  end

end

app/controllers/draft_controller.rb
class DraftController < ApplicationController

  skip_before_action :authenticate_user_from_token!

  def welcome
  end

  def new
    @draft = Draft.new
  end

  def create
    if save_new_draft
      redirect_to add_players_path(@draft)
    else
      render :new
    end
  end

  def add_players
    draft = Draft.find(params[:id])
    player = Player.new
    @facade = NewDraftFacade.new(draft, player)
  end

  def add_player
    if add_new_player_to_draft
      redirect_to add_players_path
    else
      render :add_players
    end
  end

  def review
    draft = Draft.find(params[:id])
    draft_order = DraftOrderer.generate_or_retrieve_picks(draft)
    draftables = draft.draftables
    @review = ReviewDraftFacade.new(draft_order, draftables, draft)
  end

  def start
    draft = Draft.find(params[:id])
    DraftStarter.new(draft).start

    #TODO spec out a status dashboard that the draft admin can see
    #This should redirect to it
    render text: 'Started!'
  end

  def show
    render text: 'recap'
  end

  private
  def player_params
    params.require(:player).permit(:name, :email)
  end

  def draft_params
    params.require(:draft).permit(:name)
  end

  def save_new_draft
    @draft = Draft.new(draft_params)
    @draft.save
  end

  def add_new_player_to_draft
    @draft = Draft.find(params[:id])
    if create_new_player
      add_player_to_draft
    else
      return false
    end
  end

  def create_new_player
    @player = Player.new(player_params)
    @player.save
  end

  def add_player_to_draft
    @draft.players << @player
    @draft.save
  end
end

app/views/draft/_player_errors.html.slim
.errors
  - @player.errors.full_messages.each do |e|
    .error = e

app/views/draft/add_players.html.slim
header
  h1 New Draft: Step 2
section
  h2 = @facade.draft.name
  h2 Step 2) Add Players
  - if @facade.current_players.any?
    h3 Signed up so far
    ul
      - @facade.current_players.each do |p|
        li = p.name
section
  = form_for(@facade.player, url: add_player_path) do |f|
    = render 'player_errors' if @facade.player.errors.any?
    = f.text_field :name, placeholder: 'First Name', autofocus: true
    = f.text_field :email, placeholder: 'Email'
    = f.submit 'Add player'
section.spacer
  = button_to 'Finish', add_draftable_path(@facade.draft)

app/views/draft/new.html.slim
header
  h1 New Draft: Step 1
section
  h1 What is the name of this event?
  = form_for(@draft, url: create_draft_path) do |f|
    = f.text_field :name, placeholder: 'Event Name'
    = f.submit 'Add Players'

app/views/draft/review.html.slim
header
  h1 Step 5: Start the Draft!
section
  p You're almost set. A draft order has been randomly generated. Review everything 
    below and if it looks right click Start to begin the draft. Everyone will be
    sent an email, and the first drafter will be on the clock. Good luck!
section.center-text
  h3 Draft Order
  ul
   - @review.draft_order.each do |player| 
    li = player.name
  h3 Draftables
  ul
   - @review.draftables.each do |draftable| 
     li = "#{draftable.rank}. #{draftable.name}"
  .spacer
  = button_to 'Start Draft', start_draft_path(@review.draft)

app/views/draft/welcome.html.slim
a href="#{new_draft_path}" Start New Draft