config/routes.rb
Rails.application.routes.draw do

  root 'draft#welcome'

  resources :drafts, only: [] do
    resource :recap, only: [:show]
    resources :autodrafts, only: [:index, :create, :destroy, :update], shallow: true
  end


  devise_for :players
  get 'authentication/sign_in', as: :sign_in

  get 'new/create-draft' => 'draft#new', as: :new_draft
  post 'new/create-draft' => 'draft#create', as: :create_draft
  get 'new/:id/add-players' => 'draft#add_players', as: :add_players
  post 'new/:id/add-player' => 'draft#add_player', as: :add_player
  get 'new/:draft_id/add-draftees' => 'draftables#batch_new',
    as: :add_draftable
  post 'new/:draft_id/add-draftees' => 'draftables#batch_create',
    as: :save_draftables
  get 'new/:id/review' => 'draft#review', as: :review_draft
  post 'new/:id/start' => 'draft#start', as: :start_draft

  get 'picks/:draft_id/:player_id/(:token)' => 'picks#new', as: :pick
  post 'picks/make/:draft_id/:draftable_id' => 'picks#make', as: :make_pick
  get 'picks/make/:draft_id/:player_id/:draftable_id/:token' =>
    'picks#make', as: :make_pick_from_email

  get 'players/show/:draft_id' => 'players#show', as: :player_page
  get 'players/all_picks/:draft_id' => 'players#all_picks', as: :all_picks

  if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/emails"
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  devise :rememberable
  
  alias_attribute :token, :authentication_token

  has_and_belongs_to_many :drafts
  has_many :picks

  validates :name, presence: true
  validates :email, presence: true

  before_save :update_auth_token

  def name=(value)
    super(value.titleize)
  end

  def picks_for(draft)
    picks.where(draft:draft)
  end

  def made_picks_for(draft)
      picks.where(draft:draft).where.not(draftable:nil)
  end

  private 
  def update_auth_token
    self.authentication_token = Devise.friendly_token
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :redirect_to_recap_if_draft_over

  def show
    @facade = PlayerTeamFacade.new(params[:draft_id], current_player,
                                   count: params[:count])
  end

  def all_picks
    @draft = Draft.find(params[:draft_id])
  end
end

app/views/players/all_picks.html.slim
header 
  h1 Draft Results
section.draftable-table
  ul
    - @draft.picks.each do |p|
      li
        .rank = p.number
        .name = p.player.name
        .name = p.draftable.name if p.draftable
  p
    = link_to "Back", player_page_path, class: "btn btn-block"

app/views/players/show.html.slim
section
  p
    | #{@facade.current_picker} is currently on the clock with the
    |  #{@facade.current_pick} pick.
    - if @facade.any_picks_left
      |  You're next pick is the #{@facade.your_next_pick}.
    - else
      | You have no picks left.
  p
    = link_to "Set Autodraft", @facade.autodraft_path, class: "btn btn-block"

.thin-bar Your Picks
section.draftable-table
  ul
    - @facade.picks.each do |p|
      li
        .rank = p.number
        .name = p.draftable.name if p.draftable
.thin-bar Draft Status
section.draftable-table
  ul
    - @facade.surrounding_picks.each do |p|
      li class="#{'hilighted' if p.player == current_player}"
        .rank = p.number
        .name = p.player.name
        .name = p.draftable.name if p.draftable

  p
    -if @facade.more_to_show?
      = link_to "Show More", @facade.show_more_path, class: "btn btn-block"
    = link_to "Show All", all_picks_path, class: "padded btn btn-block"