config/routes.rb
Rails.application.routes.draw do

  root 'draft#welcome'

  resources :drafts, only: [] do
    resource :recap, only: [:show]
    resources :autodrafts, only: [:index, :create, :destroy, :update], shallow: true
  end


  devise_for :players
  get 'authentication/sign_in', as: :sign_in

  get 'new/create-draft' => 'draft#new', as: :new_draft
  post 'new/create-draft' => 'draft#create', as: :create_draft
  get 'new/:id/add-players' => 'draft#add_players', as: :add_players
  post 'new/:id/add-player' => 'draft#add_player', as: :add_player
  get 'new/:draft_id/add-draftees' => 'draftables#batch_new',
    as: :add_draftable
  post 'new/:draft_id/add-draftees' => 'draftables#batch_create',
    as: :save_draftables
  get 'new/:id/review' => 'draft#review', as: :review_draft
  post 'new/:id/start' => 'draft#start', as: :start_draft

  get 'picks/:draft_id/:player_id/(:token)' => 'picks#new', as: :pick
  post 'picks/make/:draft_id/:draftable_id' => 'picks#make', as: :make_pick
  get 'picks/make/:draft_id/:player_id/:draftable_id/:token' =>
    'picks#make', as: :make_pick_from_email

  get 'players/show/:draft_id' => 'players#show', as: :player_page
  get 'players/all_picks/:draft_id' => 'players#all_picks', as: :all_picks

  if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/emails"
  end
end

app/models/autodraft.rb
class Autodraft < ActiveRecord::Base
  belongs_to :draft
  belongs_to :player
  belongs_to :draftable

  def self.available_for(pick)
    #TODO optimize query
    autodrafts = where(draft:pick.draft, player: pick.player).order(:order)
    return next_available_autodraft(autodrafts, pick)
  end

  def self.current_for(draft, player)
    #TODO optimize query
    autodrafts = where(draft: draft, player: player).order(:order)
    autodrafts.reject{|a| Pick.where(draftable: a.draftable_id).any?}
  end

  private

  def self.next_available_autodraft(autodrafts, pick)
    for autodraft in autodrafts do
      if Pick.where(draft: pick.draft, draftable: autodraft.draftable).empty?
        return autodraft
      end
    end
    return nil
  end
end

app/controllers/autodrafts_controller.rb
class AutodraftsController < ApplicationController

  def index
    @draft = Draft.find(params[:draft_id])
    @autodrafts = Autodraft.current_for(@draft, current_player)
    @top_remaining = @draft.remaining_draftables.limit(10).reject{|d|
      @autodrafts.collect(&:draftable_id).include?(d.id)
    }
    @player = current_player
  end

  def create
    draft = Draft.find(params[:draft_id])
    draftable = Draftable.find(params[:draftable_id])
    repo = AutodraftRepository.new(draft, current_player)
    repo.save(draftable)
    redirect_to draft_autodrafts_path(draft)
  end

  before_action :redirect_to_player_page_if_unauthorized_delete, only: [:destroy]

  def destroy
    autodraft = Autodraft.find(params[:id])
    repo = AutodraftRepository.new(autodraft.draft, current_player)
    repo.destroy(autodraft.id)
    redirect_to draft_autodrafts_path(autodraft.draft)
  end

  def update
    autodraft = Autodraft.find(params[:id])
    repo = AutodraftRepository.new(autodraft.draft, current_player)
    repo.move(autodraft.id, params[:direction])
    redirect_to draft_autodrafts_path(autodraft.draft)
  end

  private

  def redirect_to_player_page_if_unauthorized_delete
    autodraft = Autodraft.find(params[:id])
    if autodraft.player != current_player
      redirect_to player_page_url(autodraft.draft)
    end
  end
end

app/views/autodrafts/create.html.slim
h1 Autodrafts#create
p Find me in app/views/autodrafts/create.html.slim

app/views/autodrafts/index.html.slim
header
  h1 Set Autodraft
  p Set your autodraft list here.  When it's your turn to pick the highest
    remaining team on your autodraft list will be selected for you.  You will
    be the envy of the draft as no one has to wait for you to get out of your
    meeting to make your pick.
.thin-bar Your current autodraft list
section.draftable-table.current-autodrafts
  ul
    - @autodrafts.each do |a|
      li
        = link_to '', autodraft_path(a, direction: :up), method: :patch,
          class: 'btn fa fa-chevron-up'
        .rank = a.order
        .name = a.draftable.name
        .remove-button = button_to "Remove", autodraft_path(a), method: :delete
        = link_to '', autodraft_path(a, direction: :down), method: :patch,
          class: 'btn fa fa-chevron-down'
.thin-bar Top remaining teams
section.draftable-table.remaining-draftables
  ul
    - @top_remaining.each do |d|
      li
        .rank = d.rank
        .name = d.name
        .pick = button_to "Add", draft_autodrafts_path(@draft, draftable_id: d)
section
  .spacer
   =link_to "Back", player_page_path(@draft), class: 'btn btn-block'